"""Analyse a Syosetu novel's table of contents and generate a merge .bat script.

Each arc (章) on the index page becomes one `set chap=START-END` block that
merges the arc's chapters into a single txt file.

    python gen_merge_script.py https://ncode.syosetu.com/n9636x/
"""

import argparse
import re
from pathlib import Path

from crawler import get_chapter_groups

PROJECT_DIR = Path(__file__).parent


def _sanitize_filename(name: str) -> str:
    return re.sub(r'[\\/:*?"<>|]', "_", name).strip()


def contiguous_runs(numbers: list[int]) -> list[tuple[int, int]]:
    """Split a sorted list of chapter numbers into contiguous (start, end) runs."""
    runs: list[tuple[int, int]] = []
    for n in sorted(numbers):
        if runs and n == runs[-1][1] + 1:
            runs[-1] = (runs[-1][0], n)
        else:
            runs.append((n, n))
    return runs


def build_script(
    groups: list[tuple[str | None, list[tuple[int, str]]]],
    novel_url: str,
    number: bool = False,
) -> str:
    total = sum(len(chapters) for _, chapters in groups)
    lines = [
        "@echo off",
        "chcp 65001 >nul",
        f":: Generated by gen_merge_script.py from {novel_url}",
        f":: {len(groups)} arc(s), {total} chapter(s)",
        "",
        f":: .venv\\Scripts\\python.exe main.py {novel_url}",
        "",
    ]

    extra = " --number" if number else ""

    for index, (arc_title, chapters) in enumerate(groups, start=1):
        name = _sanitize_filename(arc_title) if arc_title else f"part{index}"
        runs = contiguous_runs([n for n, _ in chapters])

        for run_index, (start, end) in enumerate(runs, start=1):
            # An arc whose chapters are not contiguous needs one line per run.
            suffix = f"_{run_index}" if len(runs) > 1 else ""
            lines.append(f"set chap={start}-{end}")
            lines.append(
                f'.venv\\Scripts\\python.exe merge.py --chapters %chap% '
                f'--output "output/%chap% {name}{suffix}.txt"{extra}'
            )
            lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate a chapter merge .bat script from a Syosetu novel index"
    )
    parser.add_argument("url", help="Novel URL, e.g. https://ncode.syosetu.com/n9636x/")
    parser.add_argument(
        "--output",
        default=str(PROJECT_DIR / "run_merge.bat"),
        help="Path of the generated script (default: <project>/run_merge.bat)",
    )
    parser.add_argument(
        "--number",
        action="store_true",
        help="Pass --number through to merge.py (prepend chapter numbers)",
    )
    args = parser.parse_args()

    print(f"Fetching table of contents from {args.url} ...")
    groups = get_chapter_groups(args.url)

    for arc_title, chapters in groups:
        numbers = [n for n, _ in chapters]
        print(f"  {arc_title or '(no arc)'}: {min(numbers)}-{max(numbers)} ({len(chapters)} chapters)")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_script(groups, args.url, number=args.number), encoding="utf-8")
    print(f"Wrote {out}")
